// Code generated by aocgen; DO NOT EDIT.
package years

import (
	"aocgen/pkg/year2015"
	"aocgen/pkg/year2022"
	"aocgen/pkg/year2023"
)

func RegisterYears() {
	year2015.Init()
	year2022.Init()
	year2023.Init()

}
