// Code generated by aocgen; DO NOT EDIT.
package year2015

import (
	"testing"

	"aocgen/pkg/aoc"
)

func Benchmark2015Day01(b *testing.B) {
	Init()
	input := aoc.TestInput(2015, 1)
	p := aoc.NewPuzzle(2015, 1)
	b.Run("PartA", func(b *testing.B) {
		b.ResetTimer()
		for i := 0; i < b.N; i++ {
			p.PartA(input)
		}
	})
	b.Run("PartB", func(b *testing.B) {
		b.ResetTimer()
		for i := 0; i < b.N; i++ {
			p.PartB(input)
		}
	})
}
func Benchmark2015Day02(b *testing.B) {
	Init()
	input := aoc.TestInput(2015, 2)
	p := aoc.NewPuzzle(2015, 2)
	b.Run("PartA", func(b *testing.B) {
		b.ResetTimer()
		for i := 0; i < b.N; i++ {
			p.PartA(input)
		}
	})
	b.Run("PartB", func(b *testing.B) {
		b.ResetTimer()
		for i := 0; i < b.N; i++ {
			p.PartB(input)
		}
	})
}
